
#### 4. **`docs/schema.dbml`**
```plaintext
Table User {
  id        Int     [pk, increment]        // Primary key, auto-incrementing
  username  String                            // Username of the user
  playlists Playlist[]                        // Relation to playlists owned by the user
}

Table Playlist {
  id            Int     [pk, increment]    // Primary key, auto-incrementing
  name          String                        // Name of the playlist
  description   String                        // Description of the playlist
  owner         User                          // Relation to the user who owns the playlist
  tracks        Track[]                       // Relation to tracks in the playlist
}

Table Track {
  id        Int [pk, increment]              // Primary key, auto-incrementing
  name      String                          // Name of the track
  playlists Playlist[]                      // Relation to playlists that contain the track
}

Ref: User.playlists < Playlist.owner        // One-to-many relation: User to Playlists
Ref: Playlist.tracks <> Track.playlists     // Many-to-many relation: Playlist to Tracks
